LDADD+=		-L/usr/local/lib -ldbus-1
CFLAGS+=	-I/usr/local/include/dbus-1.0 \
		-I/usr/local/lib/dbus-1.0/include
PROG=           framework-dbus
SRCS=           \
		framework_debus.c

.include <bsd.prog.mk>
